server:
  port: 8202
spring:
  zipkin:
    base-url: http://localhost:8402
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: febs
    password: 123456
  application:
    name: FEBS-Server-Test
  mvc:
    async:
      request-timeout: 20000
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: febs
        password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://febs:123456@localhost:8001/register/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
  instance:
    lease-renewal-interval-in-seconds: 20
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user
feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true
