server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: FEBS-Register
  security:
    user:
      name: febs
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: febs
        password: 123456


info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always