server:
  port: 8201

spring:
  application:
    name: FEBS-Server-System
eureka:
  client:
    instance-info-replication-interval-seconds: 30
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://febs:123456@localhost:8001/register/eureka/
  instance:
    lease-renewal-interval-in-seconds: 20
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user
